from pyzeebe.exceptions.pyzeebe_exceptions import PyZeebeException


class MessageAlreadyExistsError(PyZeebeException):
    pass
